#!/usr/bin/env python3
"""Generate design tokens for web + Android from design/tokens.json (P1.3 / redesign P0).

Emits idempotently (byte-identical across runs; gate-1 re-runs it twice and diffs):
  design/generated/tokens.css            CSS custom properties — light :root + [data-theme=dark]
  design/generated/tailwind.tokens.cjs   Tailwind theme extension (semantic vars)
  design/generated/Tokens.kt             Compose Colors + dimensions (dusk child app)

Generated files are committed and never hand-edited (File 02 §2); the single source of truth
is design/tokens.json. Semantic tokens only — components never see raw hex.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
TOKENS = ROOT / "design" / "tokens.json"
OUT = ROOT / "design" / "generated"

HEADER = "Generated by scripts/gen_tokens.py from design/tokens.json — do not edit by hand."

# Semantic colour tokens emitted as CSS vars + Tailwind colors.
COLOR_KEYS = [
    "bg", "surface", "surface-2", "surface-3", "border", "border-strong",
    "text", "text-muted", "text-subtle",
    "primary", "primary-hover", "primary-soft", "on-primary",
    "calm", "calm-fg", "calm-soft",
    "neutral", "neutral-fg", "neutral-soft",
    "stress", "stress-fg", "stress-soft",
    "info", "info-fg", "info-soft",
    "scrim",
]

# Type roles in output order (display face roles first).
TYPE_ROLES = ("display", "numeral-xl", "h1", "h2", "h3", "body", "body-strong", "secondary", "caption", "mono")
DISPLAY_ROLES = {"display", "numeral-xl", "h1", "h2"}
NUMERAL_ROLES = {"numeral-xl"}
MONO_ROLES = {"mono"}
DISPLAY_ROLES = {"display", "numeral-xl", "h1", "h2"}

RADIUS_KEYS = ("chip", "control", "panel", "pill")


def pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.replace("_", "-").split("-"))


def main() -> int:
    tokens = json.loads(TOKENS.read_text())
    light: dict = tokens["color"]
    dark: dict = tokens["dark"]
    t = tokens["type"]
    m = tokens["motion"]
    focus = tokens["meta"]["focus"]
    OUT.mkdir(parents=True, exist_ok=True)
    font_sans = t["font-sans"]
    font_display = t["font-display"]

    # ---- tokens.css: :root (light) + [data-theme=dark] --------------------
    css = [f"/* {HEADER} */"]

    css.append(":root {")
    css.append("  color-scheme: light;")
    for key in COLOR_KEYS:
        css.append(f"  --{key}: {light[key]};")
    css.append("  /* type */")
    css.append(f'  --font-sans: "{t["font-sans"]}", system-ui, sans-serif;')
    css.append(f'  --font-display: "{t["font-display"]}", var(--font-sans);')
    css.append(f'  --font-mono: "{t["font-mono"]}", ui-monospace, monospace;')
    for role in TYPE_ROLES:
        spec = t[role]
        family = "mono" if role in MONO_ROLES else ("display" if role in DISPLAY_ROLES else "sans")
        tnum = " tnum" if role in NUMERAL_ROLES or role in MONO_ROLES else ""
        css.append(
            f"  --type-{role}: {spec['size']}/{spec['line-height']} var(--font-{family})"
            f"{tnum} {spec['weight']};"
        )
        css.append(f"  --type-{role}-tracking: {spec['tracking']};")
    css.append("  /* radii */")
    for key in RADIUS_KEYS:
        css.append(f"  --radius-{key}: {tokens['radius'][key]}px;")
    css.append("  /* elevation */")
    for key, value in tokens["shadow"].items():
        css.append(f"  --{key}: {value};")
    css.append("  /* motion */")
    css.append(f"  --dur-fast: {m['fast']}ms;")
    css.append(f"  --dur-base: {m['base']}ms;")
    css.append(f"  --dur-slow: {m['slow']}ms;")
    css.append(f"  --ease-out: {m['ease-out']};")
    css.append(f"  --ease-in-out: {m['ease-in-out']};")
    css.append("  /* focus ring */")
    css.append(f"  --focus-ring-width: {focus['width_px']}px;")
    css.append(f"  --focus-ring-offset: {focus['offset_px']}px;")
    css.append("}")

    css.append('')
    css.append(':root[data-theme="dark"] {')
    css.append("  color-scheme: dark;")
    for key in COLOR_KEYS:
        css.append(f"  --{key}: {dark[key]};")
    for key, value in tokens["shadow-dark"].items():
        css.append(f"  --{key}: {value};")
    css.append("}")
    (OUT / "tokens.css").write_text("\n".join(css) + "\n")

    # ---- tailwind.tokens.cjs ----------------------------------------------
    js = [f"// {HEADER}",
          "// Semantic tokens as CSS vars — components use these names; themes swap the vars.",
          "module.exports = {"]
    js.append("  colors: {")
    for key in COLOR_KEYS:
        js.append(f"    '{key}': 'var(--{key})',")
    js.append("  },")
    js.append("  fontFamily: {")
    js.append("    sans: ['" + chr(34) + font_sans + chr(34) + "', 'system-ui', 'sans-serif'],")
    js.append("    display: ['" + chr(34) + font_display + chr(34) + "', '" + chr(34) + font_sans + chr(34) + "'],")
    js.append("  },")
    js.append("  fontSize: {")
    for role in TYPE_ROLES:
        spec = t[role]
        family = "mono" if role in MONO_ROLES else ("display" if role in DISPLAY_ROLES else "sans")
        tnum = '"fontVariantNumeric": "tabular-nums",' if role in NUMERAL_ROLES or role in MONO_ROLES else ""
        js.append(
            f"    '{role}': ['var(--type-{role})', {{ 'fontFamily': 'var(--font-{family})',"
            f" 'letterSpacing': '{spec['tracking']}', {tnum} 'fontWeight': '{spec['weight']}' }}],"
        )
    js.append("  },")
    js.append("  borderRadius: {")
    for key in RADIUS_KEYS:
        js.append(f"    {key}: 'var(--radius-{key})',")
    js.append("  },")
    js.append("  boxShadow: {")
    for key in ("elev-1", "elev-2", "elev-3"):
        js.append(f"    '{key.replace('-', '')}': 'var(--{key})',")
    js.append("  },")
    js.append("  transitionDuration: {")
    js.append(f"    fast: '{m['fast']}ms',")
    js.append(f"    base: '{m['base']}ms',")
    js.append(f"    slow: '{m['slow']}ms',")
    js.append("  },")
    js.append("  transitionTimingFunction: {")
    js.append(f"    out: '{m['ease-out']}',")
    js.append(f"    inout: '{m['ease-in-out']}',")
    js.append("  },")
    js.append("};")
    (OUT / "tailwind.tokens.cjs").write_text("\n".join(js) + "\n")

    # ---- Tokens.kt ---------------------------------------------------------
    kt = [f"// {HEADER}", "package app.senseheaven.child.design", "",
          "import androidx.compose.ui.graphics.Color", "import androidx.compose.ui.unit.dp", "",
          "object Tokens {"]
    for key in COLOR_KEYS:
        value = light[key]
        if isinstance(value, str) and value.startswith("#") and len(value) == 7:
            kt.append(f"    val {pascal(key)} = Color(0xFF{value[1:].upper()})")
    kt.append("")
    for key in RADIUS_KEYS:
        kt.append(f"    val Radius{pascal(key)} = {tokens['radius'][key]}.dp")
    kt.append("")
    kt.append(f"    val FocusRingWidth = {focus['width_px']}.dp")
    kt.append(f"    val FocusRingOffset = {focus['offset_px']}.dp")
    kt.append("")
    kt.append(f"    const val FONT_SANS = \"{t['font-sans']}\"")
    kt.append(f"    const val FONT_DISPLAY = \"{t['font-display']}\"")
    kt.append(f"    const val MOTION_FAST_MS = {m['fast']}")
    kt.append(f"    const val MOTION_BASE_MS = {m['base']}")
    kt.append(f"    const val MOTION_SLOW_MS = {m['slow']}")
    kt.append("}")
    (OUT / "Tokens.kt").write_text("\n".join(kt) + "\n")

    print("generated: design/generated/{tokens.css, tailwind.tokens.cjs, Tokens.kt}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
