#!/usr/bin/env python3
"""Generate design tokens for web + Android from design/tokens.json (P1.3).

Emits idempotently (byte-identical across runs; gate-1 re-runs it twice and diffs):
  design/generated/tokens.css            CSS custom properties
  design/generated/tailwind.tokens.cjs   Tailwind theme extension (CommonJS)
  design/generated/Tokens.kt             Compose Colors + dimensions

Generated files are committed and never hand-edited (File 02 §2); the single source of truth
is design/tokens.json. Light theme only (LEAN §1.3).
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
TOKENS = ROOT / "design" / "tokens.json"
OUT = ROOT / "design" / "generated"

HEADER = "Generated by scripts/gen_tokens.py from design/tokens.json — do not edit by hand."

TYPE_ROLES = ("display", "h1", "h2", "h3", "body", "secondary", "caption")


def pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.replace("_", "-").split("-"))


def main() -> int:
    tokens = json.loads(TOKENS.read_text())
    colors: dict = tokens["color"]
    for key, value in colors.items():
        if not (isinstance(value, str) and value.startswith("#") and len(value) == 7):
            raise SystemExit(f"color {key!r} must be #RRGGBB, got {value!r}")
    t = tokens["type"]
    m = tokens["motion"]
    focus = tokens["meta"]["focus"]
    OUT.mkdir(parents=True, exist_ok=True)

    # ---- tokens.css -----------------------------------------------------
    css = [f"/* {HEADER} */", ":root {"]
    css.append("  /* colour (light theme only — LEAN §1.3) */")
    for key, value in colors.items():
        css.append(f"  --{key}: {value};")
    css.append("  /* type */")
    css.append(f'  --font-sans: "{t["font-sans"]}", system-ui, sans-serif;')
    for role in TYPE_ROLES:
        spec = t[role]
        css.append(
            f"  --type-{role}-size: {spec['size']};"
            f" --type-{role}-line: {spec['line-height']};"
            f" --type-{role}-weight: {spec['weight']};"
        )
    css.append("  /* space (4-pt grid) */")
    for i, px in enumerate(tokens["space"], start=1):
        css.append(f"  --space-{i}: {px}px;")
    css.append("  /* radii */")
    for key, px in tokens["radius"].items():
        css.append(f"  --radius-{key}: {px}px;")
    css.append("  /* shadows (light only) */")
    for key, value in tokens["shadow"].items():
        css.append(f"  --shadow-{key}: {value};")
    css.append("  /* motion */")
    css.append(f"  --motion-fast: {m['fast']}ms;")
    css.append(f"  --motion-expand: {m['expand']}ms;")
    css.append(f"  --motion-dialog: {m['dialog']}ms;")
    css.append(f"  --motion-easing: {m['easing']};")
    css.append("  /* focus ring */")
    css.append(f"  --focus-ring-width: {focus['width_px']}px;")
    css.append(f"  --focus-ring-offset: {focus['offset_px']}px;")
    css.append("}")
    (OUT / "tokens.css").write_text("\n".join(css) + "\n")

    # ---- tailwind.tokens.cjs --------------------------------------------
    js = [f"// {HEADER}", "module.exports = {"]
    js.append("  colors: {")
    for key, value in colors.items():
        js.append(f"    '{key}': '{value}',")
    js.append("  },")
    js.append("  fontFamily: {")
    js.append(f"    sans: ['\"{t['font-sans']}\"', 'system-ui', 'sans-serif'],")
    js.append("  },")
    js.append("  fontSize: {")
    for role in TYPE_ROLES:
        spec = t[role]
        js.append(
            f"    '{role}': ['{spec['size']}',"
            f" {{ lineHeight: '{spec['line-height']}', fontWeight: '{spec['weight']}' }}],"
        )
    js.append("  },")
    js.append("  spacing: {")
    for px in tokens["space"]:
        js.append(f"    '{px}': '{px}px',")
    js.append("  },")
    js.append("  borderRadius: {")
    for key, px in tokens["radius"].items():
        js.append(f"    {key}: '{px}px',")
    js.append("  },")
    js.append("  boxShadow: {")
    for key, value in tokens["shadow"].items():
        js.append(f"    {key}: '{value}',")
    js.append("  },")
    js.append("  transitionDuration: {")
    js.append(f"    fast: '{m['fast']}ms',")
    js.append(f"    expand: '{m['expand']}ms',")
    js.append(f"    dialog: '{m['dialog']}ms',")
    js.append("  },")
    js.append("  transitionTimingFunction: {")
    js.append(f"    calm: '{m['easing']}',")
    js.append("  },")
    js.append("};")
    (OUT / "tailwind.tokens.cjs").write_text("\n".join(js) + "\n")

    # ---- Tokens.kt -------------------------------------------------------
    kt = [f"// {HEADER}", "package app.senseheaven.child.design", "",
          "import androidx.compose.ui.graphics.Color", "import androidx.compose.ui.unit.dp", "",
          "object Tokens {"]
    for key, value in colors.items():
        argb = "0xFF" + value[1:].upper()
        kt.append(f"    val {pascal(key)} = Color({argb})")
    kt.append("")
    for i, px in enumerate(tokens["space"], start=1):
        kt.append(f"    val Space{i} = {px}.dp")
    kt.append("")
    for key, px in tokens["radius"].items():
        kt.append(f"    val Radius{pascal(key)} = {px}.dp")
    kt.append("")
    kt.append(f"    val FocusRingWidth = {focus['width_px']}.dp")
    kt.append(f"    val FocusRingOffset = {focus['offset_px']}.dp")
    kt.append("")
    kt.append(f"    const val FONT_SANS = \"{t['font-sans']}\"")
    kt.append(f"    const val MOTION_FAST_MS = {m['fast']}")
    kt.append(f"    const val MOTION_EXPAND_MS = {m['expand']}")
    kt.append(f"    const val MOTION_DIALOG_MS = {m['dialog']}")
    kt.append("}")
    (OUT / "Tokens.kt").write_text("\n".join(kt) + "\n")

    print("generated: design/generated/{tokens.css, tailwind.tokens.cjs, Tokens.kt}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
